const pen= [
    {
        id:10,
        image:'choti.PNG',
        data: [
            {
                p:101,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:102,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:103,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:104,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:105,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:106,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:107,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:108,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:109,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:110,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:111,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:112,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]   
    },
    {
        id:100,
        image:'TB.PNG',
        data: [
            {
                p:1,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:2,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:3,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:4,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:5,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:6,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:7,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:8,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:9,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:10,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:11,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:12,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]

    },
    {
        id:200,
        image: 'LB.PNG',
        data: [
            {
                p:13,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:14,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:15,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:16,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:17,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:18,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:19,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:20,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:21,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:22,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:23,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:24,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]
    },
    {
        id:300,
        image: 'NB.PNG',
        data: [
            {
                p:25,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:26,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:27,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:28,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:29,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:30,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:31,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:32,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:33,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:34,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:35,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:36,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]
    },
    {
        id:400,
        image: 'WS.PNG',
        data: [
            {
                p:37,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:38,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:39,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:40,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:41,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:42,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:43,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:44,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:45,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:46,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:47,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:48,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]
    },
    {
        id:500,
        image: 'ST.PNG',
        data: [
            {
                p:49,
                image: 'AW.jpg',
                description: 'Amity Winter Girls Uniform',
                rating: 5,
                price: '420',
          
            },
            {
                p:50,
                image: 'AWB.jpg',
                description: 'Amity Navy Blue Matte Blazer',
                rating: 5,
                price: '420',
            },
            {   
                p:51,
                image: 'AWF.jpeg',
                description: 'Amity Blue Full Sleeves',
                rating: 5,
                price: '420',
            },
            {
                p:52,
                image: 'AWS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:53,
                image: 'ALC.jpeg',
                description: 'Amity Lab Coat',
                rating: 5,
                price: '420',
            },
            {
                p:54,
                image: 'AT.jpg',
                description: 'Amity Grey Half Sleeves Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:55,
                image: 'AWGS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:56,
                image: 'AB.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:57,
                image: 'AHS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:58,
                image: 'AWFS.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:59,
                image: 'AWG.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
            {
                p:60,
                image: 'AWT.jpg',
                description: 'Amity Grey Sweater',
                rating: 5,
                price: '420',
            },
        ]
    },
]

export default pen